# Generated by Django 5.1.7 on 2025-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Create', 'Creación'), ('Update', 'Edición'), ('Delete', 'Eliminación')], max_length=10),
        ),
    ]
