# Generated by Django 5.1.7 on 2025-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
