# Generated by Django 5.1.7 on 2025-04-09 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.IntegerField(choices=[('1', '¿Cuál es el nombre de tu primera mascota?'), ('2', '¿En qué ciudad naciste?'), ('3', '¿Cuál es el nombre de tu madre?'), ('4', '¿Cuál fue tu primer colegio?'), ('5', '¿Cuál es tu comida favorita?'), ('6', '¿Cómo se llama tu mejor amigo de la infancia?'), ('7', '¿Cuál es tu película favorita?'), ('8', '¿Qué deporte practicabas de niño?')], max_length=2, verbose_name='Pregunta de seguridad')),
                ('security_answer', models.CharField(max_length=128, verbose_name='Respuesta de seguridad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
