# Generated by Django 5.1.7 on 2025-04-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='security_question',
            field=models.IntegerField(choices=[('1', '¿Cuál es el nombre de tu primera mascota?'), ('2', '¿En qué ciudad naciste?'), ('3', '¿Cuál es el nombre de tu madre?'), ('4', '¿Cuál fue tu primer colegio?'), ('5', '¿Cuál es tu comida favorita?'), ('6', '¿Cómo se llama tu mejor amigo de la infancia?'), ('7', '¿Cuál es tu película favorita?'), ('8', '¿Qué deporte practicabas de niño?')], max_length=2, verbose_name='Pregunta de seguridad'),
        ),
    ]
