# Generated by Django 5.1.7 on 2025-04-09 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0002_brand_created_at_brand_modified_at_brand_modified_by'),
        ('category', '0002_category_created_at_category_modified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Número de serie')),
                ('state_asset', models.CharField(max_length=255, verbose_name='Bien del estado')),
                ('status', models.BooleanField(choices=[(True, 'Operativo'), (False, 'Inoperativo')], default=True)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fk_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'Assets',
                'ordering': ['id'],
            },
        ),
    ]
