# Generated by Django 5.1.7 on 2025-03-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Número de serie')),
                ('state_asset', models.CharField(max_length=255, verbose_name='Bien del estado')),
                ('status', models.BooleanField(choices=[(True, 'Operativo'), (False, 'Inoperativo')], default=True)),
                ('observation', models.TextField(blank=True)),
                ('fk_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'Assets',
                'ordering': ['id'],
            },
        ),
    ]
