# Generated by Django 5.1.7 on 2025-03-31 21:18

import bdbackups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backup_file', models.FileField(upload_to=bdbackups.models.backup_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
